Configuring drush driver locally

diff --git a/bin/runTests b/bin/runTests
--- a/bin/runTests
+++ b/bin/runTests
@@ -1,11 +1,27 @@
 #!/bin/bash
 
 #
-# This script runs the Behat tests for docker environments.
+# This script runs the Behat tests on the local docker instance.
 #
 
+
+# Source $BASH_ENV
+source $BASH_ENV
+
+# Verbose mode and exit on errors
+set -ex
+
 # Dynamically set Behat configuration parameters
-export BEHAT_PARAMS='{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "https://localhost:8080"}, "Drupal\\DrupalExtension" : {"drush" : { "root": "web/"}}}}'
+export BEHAT_PARAMS='{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://localhost:8080" }, "Drupal\\DrupalExtension" : {"drush" :   {  "alias":  "docker.docker" }} }}'
 
+# Start headless Chrome
+echo "\n Starting Chrome in headless mode ..."
+google-chrome --disable-gpu --headless --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --no-sandbox </dev/null &>/dev/null &
 
-./vendor/bin/behat --config=tests/behat/behat-docker.yml --strict --colors  "$@"
+echo "::::::::::::::::::::::::::::::::::::::::::::::::"
+echo "Behat test site: http://localhost:8080"
+echo "::::::::::::::::::::::::::::::::::::::::::::::::"
+echo
+
+# Run the Behat tests
+./vendor/bin/behat --config=tests/behat/behat-docker.yml --strict  "$@"
